/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as CostRouteImport } from './routes/cost'
import { Route as GatewayRouteImport } from './routes/gateway'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as RouterRouteImport } from './routes/router'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SelfHealingRouteImport } from './routes/self-healing'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiMetricsRouteImport } from './routes/api/metrics'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiProjectsIdRouteImport } from './routes/api/projects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewayRoute = GatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const RouterRoute = RouterRouteImport.update({
  id: '/router',
  path: '/router',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfHealingRoute = SelfHealingRouteImport.update({
  id: '/self-healing',
  path: '/self-healing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetricsRoute = ApiMetricsRouteImport.update({
  id: '/api/metrics',
  path: '/api/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/api-keys': typeof ApiKeysRoute
  '/cost': typeof CostRoute
  '/gateway': typeof GatewayRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/observability': typeof ObservabilityRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/providers': typeof ProvidersRoute
  '/router': typeof RouterRoute
  '/security': typeof SecurityRoute
  '/self-healing': typeof SelfHealingRoute
  '/settings': typeof SettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/api-keys': typeof ApiKeysRoute
  '/cost': typeof CostRoute
  '/gateway': typeof GatewayRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/observability': typeof ObservabilityRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/providers': typeof ProvidersRoute
  '/router': typeof RouterRoute
  '/security': typeof SecurityRoute
  '/self-healing': typeof SelfHealingRoute
  '/settings': typeof SettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/api-keys': typeof ApiKeysRoute
  '/cost': typeof CostRoute
  '/gateway': typeof GatewayRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/observability': typeof ObservabilityRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/providers': typeof ProvidersRoute
  '/router': typeof RouterRoute
  '/security': typeof SecurityRoute
  '/self-healing': typeof SelfHealingRoute
  '/settings': typeof SettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/api-keys'
    | '/cost'
    | '/gateway'
    | '/history'
    | '/login'
    | '/notifications'
    | '/observability'
    | '/profile'
    | '/projects'
    | '/providers'
    | '/router'
    | '/security'
    | '/self-healing'
    | '/settings'
    | '/api/$'
    | '/api/history'
    | '/api/metrics'
    | '/api/projects'
    | '/api/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/api-keys'
    | '/cost'
    | '/gateway'
    | '/history'
    | '/login'
    | '/notifications'
    | '/observability'
    | '/profile'
    | '/projects'
    | '/providers'
    | '/router'
    | '/security'
    | '/self-healing'
    | '/settings'
    | '/api/$'
    | '/api/history'
    | '/api/metrics'
    | '/api/projects'
    | '/api/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/api-keys'
    | '/cost'
    | '/gateway'
    | '/history'
    | '/login'
    | '/notifications'
    | '/observability'
    | '/profile'
    | '/projects'
    | '/providers'
    | '/router'
    | '/security'
    | '/self-healing'
    | '/settings'
    | '/api/$'
    | '/api/history'
    | '/api/metrics'
    | '/api/projects'
    | '/api/projects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApiKeysRoute: typeof ApiKeysRoute
  CostRoute: typeof CostRoute
  GatewayRoute: typeof GatewayRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ObservabilityRoute: typeof ObservabilityRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  ProvidersRoute: typeof ProvidersRoute
  RouterRoute: typeof RouterRoute
  SecurityRoute: typeof SecurityRoute
  SelfHealingRoute: typeof SelfHealingRoute
  SettingsRoute: typeof SettingsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiMetricsRoute: typeof ApiMetricsRoute
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateway': {
      id: '/gateway'
      path: '/gateway'
      fullPath: '/gateway'
      preLoaderRoute: typeof GatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/router': {
      id: '/router'
      path: '/router'
      fullPath: '/router'
      preLoaderRoute: typeof RouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-healing': {
      id: '/self-healing'
      path: '/self-healing'
      fullPath: '/self-healing'
      preLoaderRoute: typeof SelfHealingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metrics': {
      id: '/api/metrics'
      path: '/api/metrics'
      fullPath: '/api/metrics'
      preLoaderRoute: typeof ApiMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
  }
}

interface ApiProjectsRouteChildren {
  ApiProjectsIdRoute: typeof ApiProjectsIdRoute
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsIdRoute: ApiProjectsIdRoute,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApiKeysRoute: ApiKeysRoute,
  CostRoute: CostRoute,
  GatewayRoute: GatewayRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ObservabilityRoute: ObservabilityRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  ProvidersRoute: ProvidersRoute,
  RouterRoute: RouterRoute,
  SecurityRoute: SecurityRoute,
  SelfHealingRoute: SelfHealingRoute,
  SettingsRoute: SettingsRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiMetricsRoute: ApiMetricsRoute,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
