export const ErrorCode = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_WEAK_PASSWORD: 'AUTH_WEAK_PASSWORD',

  // Organization
  ORG_NOT_FOUND: 'ORG_NOT_FOUND',
  ORG_SLUG_EXISTS: 'ORG_SLUG_EXISTS',
  ORG_MEMBER_EXISTS: 'ORG_MEMBER_EXISTS',
  ORG_UNAUTHORIZED: 'ORG_UNAUTHORIZED',

  // Project
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_SLUG_EXISTS: 'PROJECT_SLUG_EXISTS',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',

  // API Key
  APIKEY_NOT_FOUND: 'APIKEY_NOT_FOUND',
  APIKEY_EXPIRED: 'APIKEY_EXPIRED',
  APIKEY_REVOKED: 'APIKEY_REVOKED',
  APIKEY_INVALID: 'APIKEY_INVALID',

  // Provider
  PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',

  // General
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
